-- return {
--     "mfussenegger/nvim-jdtls",
--
--     config = function()
--         local configVal = {
--             cmd = { "/home/gk/.local/share/nvim/mason/packages/jdtls/config_linux" },
--             root_dir = vim.fs.dirname(vim.fs.find({ 'gradlew', '.git', 'mvnw' }, { upward = true })[1]),
--         }
--
--         require('jdtls').start_or_attach(configVal)
--     end
--
--
-- }
--
--
return {}
